server:
  port: 8088
spring:
  application:
    name: cgfy-lock
  datasource:
    name: test
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cgfy_web?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
      username: root
      password: 123456
      # 初始化连接池大小
      initial-size: 0
      # 最大链接数
      max-active: 20
      # 最小链接间隔
      min-idle: 1
      # 最大等待时间，单位是毫秒
      max-wait: 60000
#  redis:
#    cluster:
#      nodes: 172.16.4.27:7000, 172.16.4.27:7001, 172.16.4.27:7002, 172.16.4.27:7003, 172.16.4.27:7004
#    lettuce:
#      pool:
#        min-idle: 0
#        max-idle: 8
#        max-active: 20
#    timeout: 5000
