spring:
  profiles:
    active: win
  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  port: 8088

---
spring:
  profiles: win
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  freemarker:
    suffix: .html
jodconverter:
  local:
    enabled: true
    office-home: C:/Program Files (x86)/LibreOffice
    port-numbers: 8100,8101,8102
    max-tasks-per-process: 100
  store:
    path: F:/data/preview
---
spring:
  profiles: linux
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  freemarker:
    suffix: .html
jodconverter:
  local:
    enabled: true
    office-home: /usr/lib64/libreoffice
    port-numbers: 8100,8101,8102
    max-tasks-per-process: 100
  store:
    path: /data/preview