server:
  port: 8062

dubbo:
  application:
    name:  dubbo-consumer #应用名
  registry:
    address: 127.0.0.1:2181 #指定注册中心地址
    protocol: zookeeper
    check: false
  monitor:
    protocol: register #监控中心协议，如果为protocol="registry"，表示从注册中心发现监控中心地址，否则直连监控中心
  consumer:
    check:  false
    timeout: 3000 #全局超时配置
    #retries: 2 #重试次数配置


